title: "Furnace and Fugue Color Palette"
status: wip
context:
  heading1: "Primary Colors"
  heading2: "Secondary Colors"
  heading3: "Supplemental Colors"
  hex1: "#DC4929"
  hex2: "#FFB000"
  hex3: "#DAE4EC"
  hex4: "#333333"
  hex5: "#808080"
  hex6: "#4C4C4C"
  hex7: "#222222"
  hex8: "#B84121"
  hex9: "#21212166"
  hex10: "#F1F1F1"
  hex11: "#FFCD61"
  hex12: "#333333EE"
  hex13: "#FFFFFF"
  hex14: "#111111"
  hex15: "#000000"
  hsla1: "hsla(11, 72%, 51%, 1)"
  hsla2: "hsla(41, 100%, 50%, 1)"
  hsla3: "hsla(207, 32%, 89%, 1)"
  hsla4: "hsla(0, 0%, 20%, 1)"
  hsla5: "hsla(0, 0%, 50%, 1)"
  hsla6: "hsla(0, 0%, 30%, 1)"
  hsla7: "hsla(0, 0%, 13%, 1)"
  hsla8: "hsla(11, 72%, 42%, 1)"
  hsla9: "hsla(0, 0%, 13%, .4)"
  hsla10: "hsla(0, 0%, 95%, 1)"
  hsla11: "hsla(41, 100%, 69%, 1)"
  hsla12: "hsla(0, 0%, 20%, .97)"
  hsla13: "hsla(0, 100%, 100%, 1)"
  hsla14: "hsla(0, 0%, 7%, 1)"
  hsla15: "hsla(0, 0%, 0%, 1)"
  scss1: "$red"
  scss2: "$yellow"
  scss3: "$blue_light"
  scss4: "$gray"
  scss5: "$gray_medium"
  scss6: "$text_body"
  scss7: "$black"
  scss8: "$red_dark"
  scss9: "$black_transparent"
  scss10: "$gray_light"
  scss11: "$yellow_light"
  scss12: "$gray_transparent"
  scss13: "$white"
  scss14: "$black_dark"
  scss15: "$black_pure"