title: "Furnace and Fugue global table of contents"
status: wip
context:
  author1: "by Tara Nummedal and Donna Bilak"
  author2: "by Tara Nummedal"
  author3: "by Michael Gaudio"
  author4: "by Eric Bianchi"
  author5: "by Peter J. Forshaw"
  author6: "by Loren Ludwig"
  author7: "by Richard J. Oosterhoff"
  author8: "by Donna Bilak"
  description1: "Description lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae tortor et justo vestibulum."
  description2: "Description lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vitae tortor et justo vestibulum."
  heading1: "Atalanta fugiens"
  heading2: "Scholarly Essays"
  heading3: "Images"
  heading4: "Get Acquainted"
  heading5: "Additional Materials"
  subheading1: "Digital Edition"
  subheading3a: "Emblem Image Search"
  subheading3b: "My Emblem Collections"
  subheading4a: "A Biography of Michael Maier"
  subheading4b: "The Making of"
  subheading4bCitation: "Atalanta fugiens"
  subheading4c: "Introducing Alchemy"
  subheading5a: "About the Project"
  subheading5b: "Music Performance Edition"
  subheading5c: "Technical Resources"
  subheading5d: "Contact Us"
  title1: "Introduction"
  title2: "Sound and Vision"
  title3: "The Emblem in the Landscape"
  title4: "Weight, Number, Measure"
  title5: "Michael Maier and Mythoalchemy"
  title6a: "John Farmer’s"
  title6b: "Sundry waies"
  title6c: "(1591)"
  title7: "Learned Failure and the Untutored Mind"
  title8: "Chasing Atalanta"
